// Build the isolated test bundle first: npx vite build --config vite.test.config.js
// Requires Playwright locally (npm install --no-save playwright).
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'../../../firebase-ui-test-dist');const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--single-process','--disable-gpu','--disable-software-rasterizer']});
try{const context=await browser.newContext({viewport:{width:1440,height:1000}});const a=await context.newPage();const errors=[];a.on('pageerror',e=>errors.push(e.message));await a.goto(url);await a.getByRole('heading',{name:'Welcome back.'}).waitFor();await a.screenshot({path:path.resolve(__dirname,'../../../Firebase-Login-Desktop.png')});await a.setViewportSize({width:390,height:844});await a.screenshot({path:path.resolve(__dirname,'../../../Firebase-Login-Mobile.png')});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.setViewportSize({width:1440,height:1000});
const login=async page=>{await page.getByLabel('Email address').fill('owner@example.com');await page.getByLabel('Password',{exact:true}).fill('ExamplePass123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Let’s get to work.'}).waitFor();};
await a.getByLabel('Email address').fill('wrong@example.com');await a.getByLabel('Password',{exact:true}).fill('wrong');await a.getByRole('button',{name:'Sign in',exact:true}).click();await a.getByRole('alert').waitFor();await a.getByRole('button',{name:'Forgot password?'}).click();await a.getByText('If this email has an account, a reset link will arrive shortly.').waitFor();await login(a);
const nav=async(page,hash)=>{await page.evaluate(hash=>location.hash=hash,hash);await page.waitForTimeout(100);};const task=async(page,title)=>{await nav(page,'tasks');await page.getByRole('button',{name:'New task',exact:true}).first().click();await page.getByLabel('Task *',{exact:true}).fill(title);await page.getByRole('button',{name:'Save changes',exact:true}).click();};
await task(a,'From PC');await a.getByText('Cloud synced',{exact:true}).waitFor();const b=await context.newPage();b.on('pageerror',e=>errors.push(e.message));await b.goto(url);await login(b);await nav(b,'tasks');await b.getByRole('button',{name:/From PC Workspace/}).waitFor();
await a.evaluate(()=>{Object.defineProperty(navigator,'onLine',{value:false,configurable:true});window.dispatchEvent(new Event('offline'));});await task(a,'Offline PC edit');await task(b,'Phone edit');await b.getByText('Cloud synced',{exact:true}).waitFor();await a.evaluate(()=>{Object.defineProperty(navigator,'onLine',{value:true,configurable:true});window.dispatchEvent(new Event('online'));});await nav(a,'settings');await a.getByRole('heading',{name:'Two devices changed this workspace'}).waitFor();a.once('dialog',d=>d.accept());await a.getByRole('button',{name:'Back up local & use cloud'}).click();await nav(a,'tasks');await a.getByRole('button',{name:/Phone edit Workspace/}).waitFor();assert.equal(await a.getByRole('button',{name:/Offline PC edit Workspace/}).count(),0);
await nav(a,'settings');await a.getByLabel('Bank',{exact:true}).fill('Test Bank');await a.getByRole('button',{name:'Save payment details',exact:true}).click();await a.getByText('Cloud synced',{exact:true}).waitFor();await nav(b,'settings');await b.getByLabel('Bank',{exact:true}).waitFor();assert.equal(await b.getByLabel('Bank',{exact:true}).inputValue(),'Test Bank');
await a.getByRole('button',{name:'Sign out',exact:true}).click();await a.getByRole('heading',{name:'Welcome back.'}).waitFor();assert.equal(await a.evaluate(()=>localStorage.getItem('codevenient-cloud-test-owner')),null);assert.equal(await a.getByRole('navigation',{name:'Main navigation'}).count(),0);assert.deepEqual(errors,[]);console.log('PASS: login gate, invalid login, password reset UI, two-device sync, offline conflict, resolution, private settings propagation, sign-out and cache clearing. Mock Firebase adapter; no live Firebase claim.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1);});
