import test from 'node:test';
import assert from 'node:assert/strict';
import {SyncEngine} from '../src/lib/sync-engine.js';
import {emptyWorkspace,applyAction,encodeWorkspace} from '../src/lib/workspace.js';
function server(){let record=null;const listeners=new Set();return {get record(){return record;},adapter:{subscribe(fn){listeners.add(fn);queueMicrotask(()=>fn(record));return()=>listeners.delete(fn);},async save(data,expected){if((record?.version||0)!==expected){const e=new Error('Conflict');e.code='sync/conflict';e.remote=structuredClone(record);throw e;}record={data:structuredClone(data),version:expected+1};for(const fn of listeners)fn(structuredClone(record));return record.version;}}};}
function client(t,s,saved){let cache=saved;let view;const e=new SyncEngine({adapter:s.adapter,delay:60000,cache:{load:()=>cache,save:v=>{cache=structuredClone(v);}},onChange:v=>{view=v;}});e.start();t.after(()=>e.dispose());return {e,get cache(){return cache;},get view(){return view;}};}
const tick=()=>new Promise(resolve=>queueMicrotask(resolve));
const note=(e,title)=>e.change(applyAction(e.data,{type:'ADD_NOTE',payload:{title,body:'body',tag:'General'}}));
test('first device saves automatically; second device receives acknowledged records',async t=>{const s=server(),a=client(t,s),b=client(t,s);await tick();note(a.e,'First');assert.equal(a.view.status,'pending');await a.e.flush();assert.equal(a.view.status,'synced');assert.equal(b.e.data.notes[0].title,'First');assert.equal(b.e.version,1);});
test('concurrent edits preserve both versions and require explicit resolution',async t=>{const s=server(),a=client(t,s),b=client(t,s);await tick();note(a.e,'PC');note(b.e,'Phone');await a.e.flush();assert.equal(b.view.status,'conflict');assert.equal(b.e.data.notes[0].title,'Phone');assert.equal(b.e.conflict.data.notes[0].title,'PC');await b.e.flush();assert.equal(s.record.data.notes[0].title,'PC');b.e.useCloud();assert.equal(b.e.data.notes[0].title,'PC');assert.equal(b.e.dirty,false);});
test('offline edits survive reload and resume only after server version confirmation',async t=>{const s=server(),a=client(t,s);await tick();a.e.setOnline(false);note(a.e,'Offline');await a.e.flush();assert.equal(s.record,null);a.e.dispose();const b=client(t,s,a.cache);await tick();await b.e.flush();assert.equal(s.record.data.notes[0].title,'Offline');assert.equal(b.e.dirty,false);});
test('offline edits conflict if another device changed the cloud',async t=>{const s=server(),a=client(t,s);await tick();a.e.setOnline(false);note(a.e,'Local');a.e.dispose();const b=client(t,s);await tick();note(b.e,'Remote');await b.e.flush();const c=client(t,s,a.cache);await tick();assert.equal(c.view.status,'conflict');assert.equal(c.e.data.notes[0].title,'Local');c.e.keepLocal();await c.e.flush();assert.equal(s.record.version,2);assert.equal(s.record.data.notes[0].title,'Local');});
test('edits made during a pending request are not incorrectly marked synced',async t=>{const s=server();let finish;const actual=s.adapter.save;s.adapter.save=(data,version)=>new Promise(resolve=>{finish=async()=>resolve(await actual(data,version));});const a=client(t,s);await tick();note(a.e,'First');const pending=a.e.flush();note(a.e,'Second');await finish();await pending;assert.equal(a.e.dirty,true);assert.equal(a.e.data.notes.length,2);assert.equal(s.record.data.notes.length,1);s.adapter.save=actual;await a.e.flush();assert.equal(a.e.dirty,false);assert.equal(s.record.data.notes.length,2);});
test('transaction detects a conflict even when listener has not delivered it',async t=>{const s=server();const a=client(t,s);await tick();note(a.e,'Local');await s.adapter.save(applyAction(emptyWorkspace(),{type:'ADD_NOTE',payload:{title:'Remote'}}),0);a.e.conflict=null;await a.e.flush();assert.equal(a.e.conflict.data.notes[0].title,'Remote');assert.equal(a.e.data.notes[0].title,'Local');});
test('local storage failure stays visible and cloud acknowledgement is honest',async t=>{const s=server();let view;const e=new SyncEngine({adapter:s.adapter,delay:60000,cache:{load:()=>null,save:()=>{throw new Error('quota');}},onChange:v=>view=v});t.after(()=>e.dispose());e.start();await tick();note(e,'Protected');assert.match(view.localError,/storage failed/);await e.flush();assert.equal(s.record.data.notes[0].title,'Protected');assert.equal(view.status,'synced');});
test('failed cloud writes preserve pending data and can retry',async t=>{const s=server();const actual=s.adapter.save;s.adapter.save=async()=>{throw new Error('network unavailable');};const a=client(t,s);await tick();note(a.e,'Do not lose');await a.e.flush();assert.equal(a.e.dirty,true);assert.equal(a.view.status,'error');assert.equal(a.cache.data.notes[0].title,'Do not lose');s.adapter.save=actual;await a.e.flush();assert.equal(a.view.status,'synced');});
test('unknown or unconfigured users never receive seeded private data',()=>{const empty=emptyWorkspace();assert.equal(empty.projects.length,0);assert.equal(empty.notes.length,0);assert.equal(empty.invoices.length,0);assert.deepEqual(empty.settings.payment,{});});
test('oversized workspace is rejected before replacing the saved draft',()=>{const data=emptyWorkspace();data.notes=Array.from({length:10},(_,i)=>({id:String(i),title:'Large',body:'x'.repeat(100000)}));assert.throws(()=>encodeWorkspace(data),/850 KB/);});
