import { ArrowUpRight, Plus, ArrowRight, Circle, CheckCircle2, FolderKanban, Receipt, Wallet, Clock, AlertCircle } from 'lucide-react';
import { useStore } from '../store.jsx';
import { money, invoiceStatus, today } from '../lib/model.js';
export default function Dashboard({onNavigate}) {
 const {state,dispatch,sync}=useStore(); const paid=state.invoices.filter(i=>i.status==='Paid'); const open=state.invoices.filter(i=>['Sent','Overdue'].includes(invoiceStatus(i))); const overdue=open.filter(i=>invoiceStatus(i)==='Overdue');
 const active=state.projects.filter(p=>p.status==='In progress');const spent=state.expenses.reduce((s,e)=>s+Number(e.amount),0);const received=paid.reduce((s,i)=>s+i.total,0);const tasks=state.tasks.filter(t=>!t.done).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));
 const metrics=[['Collected',money(received),'Invoices marked paid',Wallet,'green'],['Outstanding',money(open.reduce((s,i)=>s+i.total,0)),`${open.length} invoices awaiting payment`,Receipt,'orange'],['Active projects',String(active.length).padStart(2,'0'),`${state.projects.filter(p=>p.status==='Delivered').length} delivered projects`,FolderKanban,'blue'],['Open tasks',String(tasks.length).padStart(2,'0'),`${tasks.filter(t=>t.dueDate&&t.dueDate<today()).length} past their due date`,Clock,'purple']];
 const groups=['Client','Prospect','Internal','Personal'];
 return <div className="page overview"><div className="page-heading"><div><div className="eyebrow">YOUR BUSINESS AT A GLANCE</div><h1>Let’s get to work<span className="accent">.</span></h1><p>Everything you need to move Codevenient forward.</p></div><button className="btn primary" onClick={()=>onNavigate('ledger','new')}><Plus size={17}/>Create invoice</button></div>
 {state.importedRecords&&<div className="import-notice"><AlertCircle size={17}/><span>Starting records are from your original dashboard. Review invoice amounts and statuses before relying on the totals.</span><button onClick={()=>onNavigate('settings')}>Review <ArrowRight size={14}/></button></div>}
 <div className="metric-grid">{metrics.map(([label,value,detail,Icon,color])=><section className="metric" key={label}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}><Icon size={18}/></span></div><strong>{value}</strong><p>{detail}</p></section>)}</div>
 <div className="overview-grid"><section className="card"><div className="section-head"><div><h2>Project pulse</h2><p>A clear view of what’s moving.</p></div><button className="text-btn" onClick={()=>onNavigate('projects')}>All projects <ArrowUpRight size={16}/></button></div><div className="pulse-layout"><div className="project-total"><strong>{state.projects.length}</strong><span>total projects</span><div className="segmented-bar">{groups.map((g,i)=><span key={g} style={{flex:state.projects.filter(p=>p.group===g).length,background:['#6263e7','#a5a5ee','#d0d2f5','#e7e8f8'][i]}}/>)}</div></div><div className="project-legend">{groups.map((g,i)=><div key={g}><span className={`legend-dot l${i}`}/><span>{g==='Client'?'Client work':g==='Prospect'?'Prospects':g}</span><strong>{state.projects.filter(p=>p.group===g).length}</strong></div>)}</div></div><div className="project-list">{active.slice(0,4).map(p=><button key={p.id} onClick={()=>onNavigate('projects')}><span className="project-initial">{p.name.slice(0,2).toUpperCase()}</span><span className="list-title">{p.name}<small>{p.stack||p.group}</small></span><span className="badge orange">In progress</span><ArrowUpRight size={16}/></button>)}{active.length===0&&<div className="empty-small">No active projects. Start one when you’re ready.</div>}</div></section>
 <section className="card focus-card"><div className="section-head"><div><div className="eyebrow">MAKE IT HAPPEN</div><h2>Your next moves</h2></div><span className="count-pill">{tasks.length}</span></div>{tasks.length?tasks.slice(0,4).map(t=><div className="task-row" key={t.id}><button className="check-button" aria-label={`Complete ${t.title}`} onClick={()=>dispatch({type:'UPDATE_TASK',id:t.id,payload:{done:true}})}><Circle size={21}/></button><div><strong>{t.title}</strong><small>{t.dueDate||'No due date'} · {t.priority||'Normal'}</small></div></div>):<div className="focus-empty"><CheckCircle2 size={34}/><h3>A little room to focus.</h3><p>Add your next task and keep the important things moving.</p></div>}<button className="btn subtle full" onClick={()=>onNavigate('tasks','new')}><Plus size={16}/>Add a task</button></section>
 <section className="card"><div className="section-head"><div><h2>Invoices to follow up</h2><p>{overdue.length?`${overdue.length} overdue · a good place to start`:'Keep an eye on upcoming payments'}</p></div><button className="text-btn" onClick={()=>onNavigate('ledger')}>View invoices <ArrowUpRight size={16}/></button></div><div className="table-wrap"><table><thead><tr><th>CLIENT / INVOICE</th><th>DUE</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{open.slice(0,4).map(i=><tr key={i.id} onClick={()=>onNavigate('ledger')}><td><strong>{i.client}</strong><small>{i.id}</small></td><td>{i.dueDate}</td><td className="numeric">{money(i.total)}</td><td><span className={`badge ${invoiceStatus(i)==='Overdue'?'red':'orange'}`}>{invoiceStatus(i)}</span></td></tr>)}</tbody></table>{!open.length&&<div className="empty-small">You’re all caught up. No outstanding invoices.</div>}</div></section>
 <section className="card cash-card"><div className="section-head"><div><h2>Cash snapshot</h2><p>All recorded activity</p></div><Wallet size={20}/></div><div className="cash-value"><span>Collected less expenses</span><strong>{money(received-spent)}</strong></div><div className="cash-line"><span><i className="green-dot"/>Collected</span><b>{money(received)}</b></div><div className="cash-line"><span><i className="orange-dot"/>Expenses</span><b>{money(spent)}</b></div><button className="text-btn" onClick={()=>onNavigate('expenses')}>Manage expenses <ArrowRight size={16}/></button></section></div>
 <footer className="page-footer"><span><span className="status-dot"/> {sync.status === "synced" ? "Cloud synced · keep regular backups" : "Changes saved locally · " + sync.status}</span><span>Built for the way you work.</span></footer></div>;
}
