import { useState, useEffect } from 'react';
import { Plus, Search, Users, Wallet, CheckSquare, Circle, CheckCircle2, Pencil, Download } from 'lucide-react';
import EntityModal from '../components/EntityModal.jsx';
import { useStore } from '../store.jsx';
import { money, today } from '../lib/model.js';
const configs={
 clients:{title:'Clients',desc:'Good relationships start with the details.',singular:'client',icon:Users,fields:[{key:'name',label:'Business / client name',required:true},{key:'contact',label:'Contact person'},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone',type:'tel'},{key:'status',label:'Relationship',type:'select',options:['Active','Lead','Inactive']},{key:'note',label:'Notes',type:'textarea'}],initial:{status:'Active'}},
 tasks:{title:'Tasks',desc:'A little structure. A lot more progress.',singular:'task',icon:CheckSquare,fields:[{key:'title',label:'Task',required:true},{key:'project',label:'Project / client'},{key:'dueDate',label:'Due date',type:'date'},{key:'priority',label:'Priority',type:'select',options:['Normal','High','Low']},{key:'note',label:'Notes',type:'textarea'}],initial:{priority:'Normal',done:false}},
 expenses:{title:'Expenses',desc:'Know where your money goes.',singular:'expense',icon:Wallet,fields:[{key:'title',label:'Description',required:true},{key:'amount',label:'Amount (R)',type:'number',required:true,min:0.01,step:0.01},{key:'category',label:'Category',type:'select',options:['Software','Hosting','Equipment','Marketing','Travel','Other']},{key:'date',label:'Date',type:'date',required:true},{key:'note',label:'Reference / notes',type:'textarea'}],initial:{category:'Software',date:today()}}
};
export default function Records({kind,intent,onIntentHandled}) {
 const {state,dispatch}=useStore();const c=configs[kind];const [modal,setModal]=useState(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');
 useEffect(()=>{if(intent==='new'){setModal('new');onIntentHandled();}},[intent,onIntentHandled]);
 const rows=state[kind].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(kind==='tasks'?(filter==='Completed'?r.done:!r.done):r.status===filter||r.category===filter)));
 const Icon=c.icon;
 const save=v=>dispatch({type:`${modal==='new'?'ADD':'UPDATE'}_${c.singular.toUpperCase()}`,id:modal?.id,payload:kind==='expenses'?{...v,amount:Number(v.amount)}:v});
 function csv(){const keys=kind==='expenses'?['date','title','category','amount','note']:['name','contact','email','phone','status'];const escape=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob([keys.join(',')+'\n'+rows.map(r=>keys.map(k=>escape(r[k])).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${kind}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <div className="page"><div className="page-heading"><div><div className="eyebrow">WORKSPACE / {c.title.toUpperCase()}</div><h1>{c.title}<span className="accent">.</span></h1><p>{c.desc}</p></div><button className="btn primary" onClick={()=>setModal('new')}><Plus size={17}/>New {c.singular}</button></div>
 <div className="records-toolbar"><div className="field-search"><Search size={17}/><input aria-label={`Search ${kind}`} placeholder={`Search ${kind}…`} value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label={`Filter ${kind}`} value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...(kind==='tasks'?['Open','Completed']:kind==='clients'?['Active','Lead','Inactive']:configs.expenses.fields[2].options)].map(x=><option key={x}>{x}</option>)}</select>{kind!=='tasks'&&<button className="btn subtle" onClick={csv}><Download size={16}/>Export CSV</button>}</div>
 {kind==='expenses'&&<div className="expense-summary"><span>Total {filter==='All'?'recorded':filter.toLowerCase()} expenses</span><strong>{money(rows.reduce((s,r)=>s+Number(r.amount),0))}</strong></div>}
 {!rows.length?<div className="card empty-state"><Icon size={35}/><h2>{query||filter!=='All'?'No matching records':`Your ${kind} belong here`}</h2><p>{query||filter!=='All'?'Try a different search or filter.':`Add your first ${c.singular} to get started.`}</p><button className="btn primary" onClick={()=>setModal('new')}><Plus size={16}/>New {c.singular}</button></div>:<div className={kind==='clients'?'client-grid':'card record-list'}>{rows.map(r=>kind==='clients'?<button className="card client-card" key={r.id} onClick={()=>setModal(r)}><div className="client-card-top"><span className="client-avatar">{r.name.slice(0,2).toUpperCase()}</span><span className="badge green">{r.status}</span></div><h2>{r.name}</h2><p>{r.contact||'Add a contact person'}</p><div className="client-meta">{r.email||'No email added'}<br/>{r.phone||'No phone added'}</div><span className="text-btn">View details <Pencil size={14}/></span></button>:<div className={`record-row ${r.done?'completed':''}`} key={r.id}>{kind==='tasks'&&<button className="check-button" aria-label={`${r.done?'Reopen':'Complete'} ${r.title}`} onClick={()=>dispatch({type:'UPDATE_TASK',id:r.id,payload:{done:!r.done}})}>{r.done?<CheckCircle2 size={22}/>:<Circle size={22}/>}</button>}<button className="record-main" onClick={()=>setModal(r)}><strong>{r.title}</strong><small>{kind==='tasks'?`${r.project||'Workspace'} · ${r.dueDate||'No due date'}`:`${r.category} · ${r.date}`}</small></button>{kind==='expenses'?<b>{money(r.amount)}</b>:<span className={`badge ${r.priority==='High'?'red':'purple'}`}>{r.done?'Completed':r.priority}</span>}<button className="icon-btn" aria-label={`Edit ${r.title}`} onClick={()=>setModal(r)}><Pencil size={16}/></button></div>)}</div>}
 {modal&&<EntityModal title={`${modal==='new'?'New':'Edit'} ${c.singular}`} fields={c.fields} initial={modal==='new'?c.initial:modal} onClose={()=>setModal(null)} onSave={save} onDelete={modal==='new'?undefined:()=>dispatch({type:`DELETE_${c.singular.toUpperCase()}`,id:modal.id})}/>}</div>;
}
