import {useState,useRef,useEffect} from 'react';
import {Download,Upload,ShieldCheck,Cloud,LogOut,CheckCircle2} from 'lucide-react';
import {useStore} from '../store.jsx';
import {downloadBackup,validateState,STORAGE_KEY} from '../lib/model.js';
import {MAX_WORKSPACE_BYTES} from '../lib/workspace.js';
export default function Settings(){
 const {state,dispatch,sync,user,signOut,cacheKey,retrySync,useCloud,keepLocal}=useStore();const [pending,setPending]=useState(null);const [error,setError]=useState('');const file=useRef();const [payment,setPayment]=useState(state.settings?.payment||{});const [paymentDirty,setPaymentDirty]=useState(false);const paymentBase=useRef(JSON.stringify(state.settings?.payment||{}));const paymentChanged=paymentDirty&&paymentBase.current!==JSON.stringify(state.settings?.payment||{});useEffect(()=>{if(!paymentDirty){setPayment(state.settings?.payment||{});paymentBase.current=JSON.stringify(state.settings?.payment||{});}},[state.settings?.payment,paymentDirty]);const bytes=new TextEncoder().encode(JSON.stringify(state)).length;
 async function restore(e){try{const f=e.target.files[0];if(!f)return;if(f.size>5000000)throw new Error('Backup exceeds 5 MB.');const parsed=JSON.parse(await f.text());setPending(validateState(parsed.state||parsed));setError('');}catch(e){setError(e.message);}e.target.value='';}
 function legacy(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)throw new Error('No earlier local workspace was found on this address. Choose a backup file instead.');setPending(validateState(JSON.parse(raw)));setError('');}catch(e){setError(e.message);}}
 return <div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">YOUR ACCOUNT & WORKSPACE</div><h1>Settings<span className="accent">.</span></h1><p>One account. The same workspace on every device.</p></div><button className="btn subtle" onClick={signOut}><LogOut size={16}/>Sign out</button></div>{error&&<div className="system-banner" role="alert">{error}</div>}
 <section className="card settings-card"><div className="section-head"><div><h2><Cloud size={21}/>Cloud connection</h2><p>{user.email}</p></div><span className={`badge ${sync.status==='synced'?'green':'orange'}`}>{sync.status}</span></div><p className="settings-help">Changes save automatically while connected. Other signed-in devices receive updates in real time. Offline edits stay on this device and are checked against the cloud when you reconnect.</p><div className="settings-row"><div><strong>Last acknowledged cloud version</strong><p>Version {sync.version} · {Math.ceil(bytes/1024)} KB of {Math.floor(MAX_WORKSPACE_BYTES/1024)} KB workspace capacity</p></div>{sync.dirty&&!sync.conflict&&<button className="btn subtle" onClick={retrySync} disabled={sync.saving}>Retry sync</button>}</div>{sync.error&&<p className="form-error" role="alert">{sync.error}</p>}
 {sync.conflict&&<div className="restore-box"><h3>Two devices changed this workspace</h3><p>Automatic syncing paused to avoid overwriting either version. Download both copies if you need to combine changes.</p><div className="dialog-actions"><button className="btn subtle" onClick={()=>downloadBackup(sync.conflict.data)}>Download cloud copy</button><button className="btn primary" onClick={()=>{if(confirm('Back up this device, then replace its records with the newer cloud version?'))useCloud();}}>Back up local & use cloud</button><button className="btn danger" onClick={()=>{if(confirm('Replace the newer cloud workspace with this device’s entire workspace? Other devices will receive this version.')){downloadBackup(sync.conflict.data);keepLocal();}}}>Back up cloud & keep local</button></div></div>}</section>
 <section className="card settings-card"><div className="section-head"><div><h2><ShieldCheck size={21}/>Backups & import</h2><p>Cloud sync is not a substitute for independent backups.</p></div></div><div className="settings-row"><div><strong>Export company workspace</strong><p>All records, notes, documents and billing settings.</p></div><button className="btn primary" onClick={()=>downloadBackup(state)}><Download size={16}/>Download backup</button></div><div className="settings-row"><div><strong>Import or restore</strong><p>Restoring replaces the signed-in workspace and syncs to all your devices.</p></div><button className="btn subtle" onClick={()=>file.current.click()}><Upload size={16}/>Choose backup</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={restore}/></div><div className="settings-row"><div><strong>Move from the previous dashboard</strong><p>Use your v2 backup, or check this browser’s earlier local records.</p></div><button className="btn subtle" onClick={legacy}>Find earlier local data</button></div>{pending&&<div className="restore-box"><h3>Review import</h3><p>{pending.projects.length} projects · {pending.invoices.length} invoices · {pending.notes.length} notes · {pending.clients.length} clients</p><button className="btn primary" disabled={!!sync.conflict||sync.saving} onClick={()=>{if(!confirm('Replace the company workspace on all devices with this backup?'))return;downloadBackup(state);if(dispatch({type:'RESTORE',payload:pending}))setPending(null);}}>Back up current & replace workspace</button><button className="btn subtle" onClick={()=>setPending(null)}>Cancel</button></div>}<div className="settings-row"><div><strong>Recover device draft</strong><p>Export the raw local snapshot if a saved draft needs repair.</p></div><button className="btn subtle" onClick={()=>{const raw=localStorage.getItem(cacheKey);if(!raw)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.download='device-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}}>Export recovery</button></div></section>
 <section className="card settings-card"><div className="section-head"><div><h2>Invoice payment details</h2><p>Stored privately with your workspace and used in PDF exports.</p></div></div><form onSubmit={e=>{e.preventDefault();if(paymentChanged){setError('Payment details changed on another device. Reload those details before saving.');return;}if(dispatch({type:'SET_SETTINGS',payload:{payment}}))setPaymentDirty(false);}}><div className="form-fields form-grid">{[['bank','Bank'],['accountHolder','Account holder'],['accountNumber','Account number'],['accountType','Account type'],['branchCode','Branch code']].map(([key,label])=><label key={key}>{label}<input maxLength={150} value={payment[key]||''} onChange={e=>{setPaymentDirty(true);setPayment(p=>({...p,[key]:e.target.value}));}}/></label>)}</div><button className="btn primary" disabled={paymentChanged} style={{marginTop:18}}>Save payment details</button>{paymentChanged&&<div className="system-banner" role="alert">Payment details changed on another device.<button type="button" onClick={()=>setPaymentDirty(false)}>Reload details</button></div>}</form></section>
 <section className="card settings-card"><div className="section-head"><div><h2>PC & phone installation</h2><p>Open the same HTTPS address and sign in with the same account.</p></div></div><p className="settings-help">Chrome / Edge on PC: Install from the browser menu. Android: Add to Home screen → Install. iPhone: Safari → Share → Add to Home Screen. First sign-in requires an internet connection. Sign out on shared devices; signing out clears this account’s cached workspace on this browser.</p></section>
 {state.importedRecords&&<section className="card settings-card"><h2>Review imported records</h2><p className="settings-help">The original invoices include dates without years and starting balances. Confirm them against your records.</p><button className="btn subtle" onClick={()=>{if(confirm('Have you verified the starting invoice amounts and statuses?'))dispatch({type:'VERIFY_RECORDS'});}}><CheckCircle2 size={16}/>I’ve reviewed the records</button></section>}</div>;
}
