import {createContext,useContext,useEffect,useState} from 'react';
import {LockKeyhole,ArrowRight,Cloud,MonitorSmartphone} from 'lucide-react';
import {observeUser,configured,login,resetPassword,friendlyError} from '../lib/firebase.js';
import logo from '../assets/logo-icon.png';
const AuthContext=createContext(null);
export const useAuth=()=>useContext(AuthContext);
export default function AuthGate({children}){
 const [user,setUser]=useState(null);const [checking,setChecking]=useState(configured);const [error,setError]=useState('');const [info,setInfo]=useState('');const [busy,setBusy]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [remember,setRemember]=useState(false);
 useEffect(()=>{if(!configured)return;return observeUser(u=>{setUser(u);setChecking(false);setPassword('');},e=>{setError(friendlyError(e));setChecking(false);});},[]);
 if(user)return <AuthContext.Provider value={user}>{children}</AuthContext.Provider>;
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await login(email,password,remember);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 async function reset(){setError('');setInfo('');if(!email.trim()){setError('Enter your email address first.');return;}setBusy(true);try{await resetPassword(email);setInfo('If this email has an account, a reset link will arrive shortly.');}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 return <div className="login-screen"><div className="login-story"><div className="brand"><img src={logo} alt=""/><span>codevenient<span className="brand-sub">BUSINESS WORKSPACE</span></span></div><div><div className="eyebrow">ONE WORKSPACE. EVERY DEVICE.</div><h1>Your business.<br/>Always with you<span>.</span></h1><p>Pick up where you left off. Projects, invoices and the details that keep your company moving.</p><div className="login-features"><span><Cloud size={19}/>Automatic cloud saving</span><span><MonitorSmartphone size={19}/>PC and phone, connected</span><span><LockKeyhole size={19}/>Your private workspace</span></div></div><small>Codevenient Consulting</small></div><div className="login-panel"><div className="login-card"><span className="login-lock"><LockKeyhole size={24}/></span><h2>{checking?'Opening your workspace…':configured?'Welcome back.':'Connect your workspace.'}</h2><p>{checking?'Checking your sign-in session.':configured?'Sign in to continue to your company workspace.':'Firebase setup is required before this app can open.'}</p>{!configured?<div className="setup-notice"><p>Follow <strong>FIREBASE-SETUP.md</strong> in the project to connect Authentication and Firestore. The app stays locked until configured.</p><p>Company records are imported after sign-in; they are not included in this website.</p></div>:!checking&&<form onSubmit={submit} className="login-form"><label>Email address<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.co.za"/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="login-options"><label><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember this device</label><button type="button" onClick={reset} disabled={busy}>Forgot password?</button></div>{error&&<p className="form-error" role="alert">{error}</p>}{info&&<p role="status">{info}</p>}<button className="btn primary full" disabled={busy}>{busy?'Please wait…':'Sign in'}<ArrowRight size={17}/></button><small>Access is limited to approved company accounts.</small></form>}</div><small className="login-footer">Convenient Code. Infinite Potential.</small></div></div>;
}
