import { useEffect, useState } from 'react';
import { LayoutDashboard, FolderKanban, FileText, Receipt, StickyNote, Settings, Users, CheckSquare, Wallet, Search, Sun, Moon, ChevronRight, Download, X, Menu, ArrowUpRight } from 'lucide-react';
import logo from '../assets/logo-icon.png';
import { useStore } from '../store.jsx';
export const NAV = [ ['dashboard','Overview',LayoutDashboard], ['projects','Projects',FolderKanban], ['clients','Clients',Users], ['tasks','Tasks',CheckSquare], ['ledger','Invoices',Receipt], ['expenses','Expenses',Wallet], ['proposals','Documents',FileText], ['notes','Notes',StickyNote], ['settings','Settings',Settings] ];
export default function Shell({active,onNavigate,children}) {
 const {state,dispatch,storageError,tabConflict,sync}=useStore();
 const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const [install,setInstall]=useState(null); const [online,setOnline]=useState(navigator.onLine);
 useEffect(()=>{ const prompt=e=>{e.preventDefault();setInstall(e);};const net=()=>setOnline(navigator.onLine);window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('online',net);window.addEventListener('offline',net);return()=>{window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('online',net);window.removeEventListener('offline',net);};},[]);
 const nav=id=>{onNavigate(id);setMenu(false);setQuery('');};
 const results=query.trim() ? ['projects','clients','invoices','proposals','notes','tasks'].flatMap(k=>state[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=>({id:r.id,label:r.name||r.title||`${r.id} · ${r.client}`,section:k==='invoices'?'ledger':k}))).slice(0,8):[];
 return <div className="workspace"><a className="skip-link" href="#content">Skip to content</a><aside className={`sidebar ${menu?'open':''}`}>
 <button className="brand" onClick={()=>nav('dashboard')}><img src={logo} alt=""/><span>codevenient<span className="brand-sub">BUSINESS WORKSPACE</span></span></button>
 <div className="workspace-label">WORKSPACE <span>01</span></div><nav aria-label="Main navigation">{NAV.map(([id,label,Icon],i)=><button key={id} className={`nav-item ${active===id?'active':''} ${i===4?'nav-break':''}`} aria-current={active===id?'page':undefined} onClick={()=>nav(id)}><Icon size={19}/><span>{label}</span>{id==='tasks'&&state.tasks.filter(t=>!t.done).length>0&&<small>{state.tasks.filter(t=>!t.done).length}</small>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="local-label"><span className={`status-dot ${sync.status}`}/>{({synced:"Cloud synced",saving:"Saving to cloud…",pending:"Waiting to save",offline:"Offline · saved here",conflict:"Sync needs attention",error:"Sync error",connecting:"Connecting…"})[sync.status]||"Connecting…"}</div><p>Your business, in one place.</p>{install&&<button className="btn subtle" onClick={async()=>{await install.prompt();setInstall(null);}}><Download size={16}/>Install app</button>}<button className="profile" onClick={()=>nav('settings')}><span className="avatar">BN</span><span>Bongani Nduna<small>Codevenient Consulting</small></span><ChevronRight size={15}/></button></div></aside>
 {menu&&<button className="menu-scrim" aria-label="Close menu" onClick={()=>setMenu(false)}/>}
 <div className="main-area"><header className="topbar"><button className="icon-btn mobile-menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={22}/></button><div className="breadcrumb">Workspace <ChevronRight size={14}/><strong>{NAV.find(n=>n[0]===active)?.[1]}</strong></div><div className="top-actions"><div className="global-search"><Search size={17}/><input aria-label="Search workspace" placeholder="Search your workspace…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}{query&&<div className="search-results"><small>Matching records · open section to view</small>{results.length?results.map(r=><button key={r.section+r.id} onClick={()=>nav(r.section)}><span>{r.label}<small>{r.section}</small></span><ArrowUpRight size={15}/></button>):<p>No records found.</p>}</div>}</div><button className="icon-btn" aria-label="Toggle colour theme" onClick={()=>dispatch({type:'SET_THEME',payload:state.theme==='dark'?'light':'dark'})}>{state.theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><span className="avatar small">BN</span></div></header>
 {(sync.conflict||sync.error)&&<div className="system-banner" role="alert">{sync.conflict?"Another device saved changes. Your local edits are safe; resolve the conflict in Settings.":sync.error}<button onClick={()=>nav("settings")}>Open Settings</button></div>}
 {(!online||storageError||tabConflict)&&<div className="system-banner" role="alert">{storageError|| (tabConflict?'This workspace changed in another tab. Reload to use the latest data.':'You’re offline. Your changes stay on this device.')}{tabConflict&&<button onClick={()=>location.reload()}>Reload</button>}</div>}
 <main id="content" tabIndex="-1">{children}</main><nav className="bottom-nav" aria-label="Mobile navigation">{NAV.filter(n=>['dashboard','projects','ledger','tasks'].includes(n[0])).map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>nav(id)}><Icon size={21}/>{label}</button>)}<button onClick={()=>setMenu(true)}><Menu size={21}/>More</button></nav></div></div>;
}
